version: '3.8'

services:
  php:
    image: gercol22/clouxter-test-php:1.0
    container_name: php_container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: gercol22/clouxter-test-mysql:1.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sample
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
    ports:
      - "3306:3306"
